runtime: nodejs20

automatic_scaling:
  max_instances: 1

handlers:
- url: /
  static_files: dist/hello-world/index.html
  upload: dist/hello-world/index.html

- url: /(.*)
  static_files: dist/hello-world/\1
  upload: dist/hello-world/(.*)