runtime: nodejs18
api_version: 1
handlers:
  - url: /
    static_files: dist/hello-world/index.html
    upload: dist/hello-world/index.html
  - url: /
    static_dir: dist/hello-world
skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE